// Settings
export const CLEAN_STORE = 'CLEAN_STORE';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_SIMMER_VISIBLE = 'SET_SIMMER_VISIBLE'
export const GET_TERMS_CONDITION = 'GET_TERMS_CONDITION';
export const SET_TERMS_CONDITION = 'SET_TERMS_CONDITION';
export const GET_SPLASH = 'GET_SPLASH';


//User
export const GET_WALLET_RECHARGE_OFFERS = 'GET_WALLET_RECHARGE_OFFERS';
export const SET_WALLET_RECHARGE_OFFERS = 'SET_WALLET_RECHARGE_OFFERS';
export const ON_WALLET_RECHARGE = 'ON_WALLET_RECHARGE';
export const SET_PAYMENT_TYPE = 'SET_PAYMENT_TYPE';
export const GET_USER_KYC = 'GET_USER_KYC';
export const SET_USER_KYC = 'SET_USER_KYC';
export const UPDATE_USER_KYC = 'UPDATE_USER_KYC';
export const UPLOAD_USER_KYC_IMAGES = 'UPLOAD_USER_KYC_IMAGES';

//! Video 
export const GET_VIDEO_CATEGORY = 'GET_VIDEO_CATEGORY';
export const SET_VIDEO_CATEGORY = 'SET_VIDEO_CATEGORY';

export const GET_SUB_CATEGORY_BY_CATEGORY_ID = 'GET_SUB_CATEGORY_BY_CATEGORY_ID';
export const SET_SUB_CATEGORY_BY_CATEGORY_ID = 'SET_SUB_CATEGORY_BY_CATEGORY_ID';

export const GET_VIDEO_CATEGORY_BY_CATEGORY_ID = 'GET_VIDEO_CATEGORY_BY_CATEGORY_ID';
export const SET_VIDEO_CATEGORY_BY_CATEGORY_ID = 'SET_VIDEO_CATEGORY_BY_CATEGORY_ID';

//* Podcast

export const GET_AUDIO = 'GET_AUDIO';
export const SET_AUDIO = 'SET_AUDIO';
export const GET_AUDIO_BY_ID = 'GET_AUDIO_BY_ID';
export const SET_AUDIO_BY_ID = 'SET_AUDIO_BY_ID';
export const GET_FAVOURITE_AUDIO = 'GET_FAVOURITE_AUDIO';

// ! banners
export const GET_BANNER = 'GET_BANNER';
export const SET_BANNER = 'SET_BANNER';

// * Registration
export const GET_COUNTRY = 'GET_COUNTRY'
export const SET_COUNTRY = 'SET_COUNTRY'
export const GET_STATE = 'GET_STATE'
export const SET_STATE = 'SET_STATE'
export const USER_REGISTER = 'USER_REGISTER'
export const GET_PROFILE = 'GET_PROFILE'
export const SET_PROFILE = 'SET_PROFILE'

//Auth

export const ON_LOGIN = 'ON_LOGIN'
export const ON_OTP_VERIFICATION = 'ON_OTP_VERIFICATION'
export const ON_RESEND = 'ON_RESEND'
export const ON_PROFILE_UPDATE = 'ON_PROFILE_UPDATE'
export const SET_OTP = 'SET_OTP'

//* News

export const GET_BREAKING_NEWS = 'GET_BREAKING_NEWS'
export const SET_BREAKING_NEWS = 'SET_BREAKING_NEWS'
export const GET_NEWS_CATEGORY = 'GET_NEWS_CATEGORY'
export const SET_NEWS_CATEGORY = 'SET_NEWS_CATEGORY'
export const GET_NEWS_CATEGORY_BY_ID = 'GET_NEWS_CATEGORY_BY_ID'
export const SET_NEWS_CATEGORY_BY_ID = 'SET_NEWS_CATEGORY_BY_ID'

// ! Recharge

//Mobile Recharge
export const GET_DEVICE_CONTACTS = 'GET_DEVICE_CONTACTS'
export const SET_DEVICE_CONTACTS = 'SET_DEVICE_CONTACTS'
export const SET_MASTER_DEVICE_CONTACTS = 'SET_MASTER_DEVICE_CONTACTS'
export const GET_MOBILE_PLANS = 'GET_MOBILE_PLANS'
export const SET_MOBILE_PLANS = 'SET_MOBILE_PLANS'
export const SET_MASTER_MOBILE_PLANS = 'SET_MASTER_MOBILE_PLANS'

export const GET_RECHARGE = 'GET_RECHARGE'
export const SET_RECHARGE = 'SET_RECHARGE'
export const ON_RAZORPAY = 'ON_RAZORPAY'
export const SET_RAZORPAY = 'SET_RAZORPAY'
export const GET_RECHARGE_REQUEST_FIELDS = 'GET_RECHARGE_REQUEST_FIELDS'
export const SET_RECHARGE_REQUEST_FIELDS = 'SET_RECHARGE_REQUEST_FIELDS'
export const GET_RECHARGE_BILL_DETAILS = 'GET_RECHARGE_BILL_DETAILS'
export const SET_RECHARGE_BILL_DETAILS = 'SET_RECHARGE_BILL_DETAILS'
export const ON_CYRUS_RECHARGE = 'ON_CYRUS_RECHARGE'
// dth Recharge
export const GET_DTH_OPERATOR = 'GET_DTH_OPERATOR'
export const SET_DTH_OPERATOR = 'SET_DTH_OPERATOR'
export const GET_DTH_BILL_DETAILS = 'GET_DTH_BILL_DETAILS'
export const SET_DTH_VALIDATION = 'SET_DTH_Validation'
export const GET_DTH_Validation = 'GET_DTH_Validation'

//FastTag
export const ON_FASTTAG_RECHARGE = 'ON_FASTTAG_RECHARGE'
export const GET_FASTTAG_OPERATOR = 'GET_FASTTAG_OPERATOR'
export const SET_FASTTAG_OPERATOR = 'SET_FASTTAG_OPERATOR'

//Electric City
export const GET_ELECTRICITY_OPERATOR = 'GET_ELECTRICITY_OPERATOR'
export const SET_ELECTRICITY_OPERATOR = 'SET_ELECTRICITY_OPERATOR'
export const SET_TOKEN = "SET_TOKEN"

// Gas
export const GET_GAS_OPERATOR = 'GET_GAS_OPERATOR'
export const SET_GAS_OPERATOR = 'SET_GAS_OPERATOR'


export const GET_OPERATOR = 'GET_OPERATOR'
export const SET_OPERATOR = 'SET_OPERATOR'
export const GET_BILL_DETAILS = 'GET_BILL_DETAILS'
export const SET_BILL_DETAILS = 'SET_BILL_DETA'
//  operator and circle 

export const SET_OPT = 'SET_OPT'
export const SET_CIRCLE = 'SET_CIRCLE'
export const GET_OPT = 'SET_OPT'
export const GET_CIRCLE = 'SET_CIRCLE'
export const SET_BILLDATA = 'SET_BILLDATA'
export const GET_BILLDATA = 'GET_BILLDATA'
export const GET_POSTPAID_OPERATOR = 'GET_POSTPAID_OPERATOR'
export const SET_POSTPAID_OPERATOR = 'SET_POSTPAID_OPERATOR'

// ! history data 

export const GET_HISTORY_DATA = 'GET_HISTORY_DATA'
export const SET_HISTORY_DATA = 'SET_HISTORY_DATA'

// * Flight
export const SET_FLIGHT_API_TYPE = 'SET_FLIGHT_API_TYPE'
export const GET_AIRPOT_CITEST = 'GET_AIRPOT_CITEST'
export const SET_AIRPOT_CITEST = 'SET_AIRPOT_CITEST'
export const SET_DEPARTURE_FROM = 'SET_DEPARTURE_FROM'
export const SET_DEPARTURE_TO = 'SET_DEPARTURE_TO'
export const GET_FLIGHT_LIST_DATA = 'GET_FLIGHT_LIST_DATA'
export const SET_FLIGHT_LIST_DATA = 'SET_FLIGHT_LIST_DATA'
export const SET_FLIGHTS_DATE_DATA = 'SET_FLIGHTS_DATE_DATA'
export const GET_FLIGHT_DATA = 'GET_FLIGHT_DATA'
export const SET_FLIGHT_DATA = 'SET_FLIGHT_DATA'
export const GET_RETURN_FLIGHT_DATA = 'GET_RETURN_FLIGHT_DATA'
export const SET_RETURN_FLIGHT_DATA = 'SET_RETURN_FLIGHT_DATA'
export const SET_FLIGHT_CONTACT_DETAILS = 'SET_FLIGHT_CONTACT_DETAILS'
export const SET_FLIGHT_PASSENGER = 'SET_FLIGHT_PASSENGER'
export const GET_FLIGHT_FARE_RULES = 'GET_FLIGHT_FARE_RULES'
export const SET_FLIGHT_FARE_RULES = 'SET_FLIGHT_FARE_RULES'
export const GET_FLIGHT_FARE_QUOTE = 'GET_FLIGHT_FARE_QUOTE'
export const SET_SELECTED_FLIGHT = 'SET_SELECTED_FLIGHT'
export const SET_SELECTED_RETURN_FLIGHT = 'SET_SELECTED_RETURN_FLIGHT'
export const SET_REQUESTING_TICKET_VISIBLE = 'SET_REQUESTING_TICKET_VISIBLE'
export const BOOK_FLIGHT = 'BOOK_FLIGHT'
export const GET_BOOKED_FLIGHT = 'GET_BOOKED_FLIGHT'
export const SET_BOOKED_FLIGHT = 'SET_BOOKED_FLIGHT'
export const GET_FLIGHT_BOOKING_DETAILS = 'GET_FLIGHT_BOOKING_DETAILS'
export const SET_FLIGHT_BOOKING_DETAILS = 'SET_FLIGHT_BOOKING_DETAILS'
export const SET_ACTIVE_SSR_TAB = 'SET_ACTIVE_SSR_TAB'
export const SET_FLIGHT_SSR_DATA = 'SET_FLIGHT_SSR_DATA'
export const SET_RETURN_FLIGHT_SSR_DATA = 'SET_RETURN_FLIGHT_SSR_DATA'
export const SET_FLIGHT_SSR_SELECTED_DATA = 'SET_FLIGHT_SSR_SELECTED_DATA'
export const SET_INTERNATIONAL_RETURN_FLIGHTS = 'SET_INTERNATIONAL_RETURN_FLIGHTS'
// ! Delete Account

export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'

// Hotel
export const ON_HOTEL_HOME_SEARCH = 'ON_HOTEL_HOME_SEARCH'
export const SET_HOTEL_HOME_INPUT = 'SET_HOTEL_HOME_INPUT'
export const ON_HOTEL_HOME = 'ON_HOTEL_HOME'
export const SET_HOTEL_HOME = 'SET_HOTEL_HOME'
export const ON_HOTEL_SEARCH = 'ON_HOTEL_SEARCH'
export const SET_HOTEL_SEARCH = 'SET_HOTEL_SEARCH'
export const GET_HOTEL_DETAILS = 'GET_HOTEL_DETAILS'
export const SET_HOTEL_DETAILS = 'SET_HOTEL_DETAILS'
export const GET_HOTEL_BOOK_SEARCH = 'GET_HOTEL_BOOK_SEARCH'
export const SET_HOTEL_BOOK_SEARCH = 'SET_HOTEL_BOOK_SEARCH'
export const SET_HOTEL_ALL = 'SET_HOTEL_ALL';
export const GET_HOTEL_ALL = 'GET_HOTEL_ALL';
export const ON_BOOK_CONFIRM = 'ON_BOOK_CONFRIM'
export const SET_BOOK_CONFIRM = 'SET_BOOK_CONFIRM'
export const SET_HOTEL_HOME_LOADING = 'SET_HOTEL_HOME_LOADING'
export const GET_HOTEL_PRE_BOOK = 'GET_HOTEL_PRE_BOOK'
export const SET_HOTEL_PRE_BOOK = 'SET_HOTEL_PRE_BOOK'
export const ON_HOTEL_BOOK_PAYMENT = 'ON_HOTEL_BOOK_PAYMENT'
export const SET_HOTEL_BOOK_PAYMENT = 'SET_HOTEL_BOOK_PAYMENT'
export const ON_HOTEL_AUTH = 'ON_HOTEL_AUTH';
export const SET_HOTEL_AUTH = 'SET_HOTEL_AUTH';
export const GET_HOTEL_LIST_DETAILS = 'GET_HOTEL_LIST_DETAILS'
export const SET_HOTEL_LIST_DETAILS = 'SET_HOTEL_LIST_DETAILS'
export const ON_HOTEL_CANCEL = 'ON_HOTEL_CANCEL';
export const SET_HOTEL_CANCEL = 'SET_HOTEL_CANCEL';

export const ON_HOTEL_PAYMENT = 'ON_HOTEL_PAYMENT';
export const SET_HOTEL_PAYMENT = 'SET_HOTEL_PAYMENT';

export const GET_METRO_OPERATORS = 'GET_METRO_OPERATORS'
export const SET_METRO_OPERATORS = 'SET_METRO_OPERATORS'

//History 
export const GET_RECHARGE_HISTORY = 'GET_RECHARGE_HISTORY'
export const SET_RECHARGE_HISTORY = 'SET_RECHARGE_HISTORY'


//Cyrus Flight API

export const GET_CYRUS_FLIGHT_LIST_DATA = 'GET_CYRUS_FLIGHT_LIST_DATA'
export const SET_CYRUS_FLIGHT_LIST_DATA = 'SET_CYRUS_FLIGHT_LIST_DATA'

export const GET_FARERULE_DATA = 'GET_FARERULE_DATA'
export const SET_FARERULE_DATA = 'SET_FARERULE_DATA'

export const GET_REPRICE_DATA = 'GET_REPRICE_DATA'
export const SET_REPRICE_DATA = 'SET_REPRICEE_DATA'

export const GET_SEATMAP_DATA = 'GET_SEATMAP_DATA'
export const SET_SEATMAP_DATA = 'SET_SEATMAP_DATA'

export const GET_SSR_DATA = 'GET_SSR_DATA'
export const SET_SSR_DATA = 'SET_SSR_DATA'

export const GET_FLIGHT_BOOKING_DATA = 'GET_FLIGHT_BOOKING_DATA'
export const SET_FLIGHT_BOOKING_DATA = 'SET_FLIGHT_BOOKING_DATA'

export const GET_REPRINT_DATA = 'GET_REPRINT_DATA'
export const SET_REPRINT_DATA = 'SET_REPRINT_DATA'

// shopping 
export const GET_SHOPPING_CATEGORY_DATA = 'GET_SHOPPING_CATEGORY_DATA' 
export const SET_SHOPPING_CATEGORY_DATA = 'SET_SHOPPING_CATEGORY_DATA' 

export const GET_SHOPPING_PRODUCT_DATA = 'GET_SHOPPING_PRODUCT_DATA' 
export const SET_SHOPPING_PRODUCT_DATA = 'SET_SHOPPING_PRODUCT_DATA' 

export const GET_ADD_CART_DATA = 'GET_ADD_CART_DATA' 
export const SET_ADD_CART_DATA = 'SET_ADD_CART_DATA' 

export const GET_ADD_TO_CART_DATA = 'GET_ADD_TO_CART_DATA' 
export const SET_ADD_TO_CART_DATA = 'SET_ADD_TO_CART_DATA' 
export const GET_DECREASE_CART_DATA = 'GET_DECREASE_CART_DATA ' 
export const SET_DECREASE_CART_DATA = 'SET_DECREASE_CART_DATA'
 
export const GET_REMOVE_CART_DATA = 'GET_REMOVE_CART_DATA ' 
export const SET_REMOVE_CART_DATA = 'SET_REMOVE_CART_DATA' 

export const GET_ADD_ADDRESS_DATA = 'GET_ADD_ADDRESS_DATA' 
export const SET_ADD_ADDRESS_DATA = 'SET_ADD_ADDRESS_DATA' 

export const GET_ORDER_DATA = 'GET_ORDER_DATA' 
export const SET_ORDER_DATA = 'SET_ORDER_DATA' 

// live
export const GET_LIVE_VIDEO_DATA = 'GET_LIVE_VIDEO_DATA' 
export const SET_LIVE_VIDEO_DATA = 'SET_LIVE_VIDEO_DATA' 

// Pooja

export const GET_POOJA_DATA = 'GET_POOJA_DATA' 
export const SET_POOJA_DATA = 'SET_POOJA_DATA' 


// Order
export const ORDER_CART = 'ORDER_CART'
export const ORDER_POOJA = 'ORDER_POOJA'
export const ORDER_YATRA = 'ORDER_YATRA'


//Admin Static Pages
export const GET_ABOUT_DATA = 'GET_ABOUT_DATA' 
export const SET_ABOUT_DATA = 'SET_ABOUT_DATA' 

export const GET_PRIVACY_DATA = 'GET_PRIVACY_DATA' 
export const SET_PRIVACY_DATA = 'SET_PRIVACY_DATA' 

export const GET_REFUND_DATA = 'GET_REFUND_DATA' 
export const SET_REFUND_DATA = 'SET_REFUND_DATA' 

export const GET_DAILY_DARSHAN_DATA = 'GET_DAILY_DARSHAN_DATA' 
export const SET_DAILY_DARSHAN_DATA = 'SET_DAILY_DARSHAN_DATA' 


//Yarta 

export const GET_YATRA_DATA = 'GET_YATRA_DATA' 
export const SET_YATRA_DATA = 'SET_YATRA_DATA' 

export const GET_PACKAGE_DATA = 'GET_PACKAGE_DATA' 
export const SET_PACKAGE_DATA = 'SET_PACKAGE_DATA' 


// CONSULTANT

export const GET_CONSULTANT_DATA = 'GET_CONSULTANT_DATA ' 
export const SET_CONSULTANT_DATA = 'SET_CONSULTANT_DATA'