export const validations = {
  name: /^[a-zA-Z\s.'-]{3,30}$/,
  email: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  phoneNumber: /^[6-9]\d{9}$/,
  address: /^[\w\s.'-]{1,60}$/g,
  city: /^[a-zA-Z\s.'-]+$/
}

export const Sanchardata = [
  { id: 1, name: 'Podcast', icon: require('../assests/icons/svg/podcast.png') },
  { id: 2, name: 'Video', icon: require('../assests/icons/svg/video.png') },
  { id: 3, name: 'News', icon: require('../assests/icons/svg/news.png'), },
  { id: 4, name: 'Live', icon: require('../assests/icons/svg/live.png'), },
];
export const brandData = [
  { id: 1, name: 'Health' },
  { id: 2, name: 'Technology' },
  { id: 3, name: 'Finance' },
  { id: 4, name: 'Arts' },
  { id: 5, name: 'Sports' },
  { id: 6, name: 'Bollywood' },
  { id: 7, name: 'Yatra' },
];
export const newsdata = [
  { id: 1, name: 'Health', image: require('../assests/images/newsperson.png') },
  { id: 2, name: 'Technology', image: require('../assests/images/newsperson.png') },
  { id: 3, name: 'Finance', image: require('../assests/images/newsperson.png') },
  { id: 4, name: 'Arts', image: require('../assests/images/newsperson.png') },
  { id: 5, name: 'Sports', image: require('../assests/images/newsperson.png') },
  { id: 6, name: 'Bollywood', image: require('../assests/images/newsperson.png') },
  { id: 7, name: 'Yatra', image: require('../assests/images/newsperson.png') },
];
export const bannerData = [
  { icon: require('../assests/images/banner.png') },
];
// export const HomebannerData = [
//   { icon: require('../assests/images/devkinand.png') },
// ];
export const songdata = [
  { id: 1, name: 'Pune', icon: require('../assests/images/hanuman.png') },
  { id: 2, name: 'bhajan', icon: require('../assests/images/hanuman.png') },
  { id: 3, name: 'biru', icon: require('../assests/images/hanuman.png') },
  { id: 4, name: 'kishor kumar', icon: require('../assests/images/hanuman.png') },
  { id: 5, name: 'kishor kumar', icon: require('../assests/images/hanuman.png') },
  { id: 6, name: 'kishor kumar', icon: require('../assests/images/hanuman.png') },
  { id: 8, name: 'kishor kumar', icon: require('../assests/images/hanuman.png') },
];
export const ReligiosData = [
  { id: 1, name: 'VSSCT', icon: require('../assests/icons/svg/vcct.png'), value: 'VSSCT' },
  { id: 2, name: 'Consultant', icon: require('../assests/icons/svg/consultancy.png'), value: 'Consultancy' },
  { id: 3, name: 'Divya Vardhan', icon: require('../assests/icons/svg/vidya.png'), value: 'Divya Vardhan' },
  { id: 4, name: 'Daily Darshan', icon: require('../assests/icons/svg/daily.png'), value: 'dailydarshan' },

];
export const YatraData = [
  { id: 1, name: 'Hotel', value: 'HotelSearch', icon: require('../assests/icons/svg/hotel.png') },
  { id: 2, name: 'Yatra', value: 'Yatra', icon: require('../assests/icons/svg/yatra.png') },
  { id: 3, name: 'Shopping', value: 'Shopping', icon: require('../assests/icons/svg/shopping.png') },
  { id: 4, name: 'Pooja', value: 'Pooja', icon: require('../assests/icons/svg/pooja.png') },

];
export const Recharge = [
  // { id: 1, name: 'Recharge', value: 'Rechargebill', icon: require('../assests/icons/svg/recharge.png') },
  { id: 1, name: 'Recharge', value: 'Recharge', icon: require('../assests/icons/svg/recharge.png') },
  { id: 2, name: 'Electricity', value: 'Electricity', icon: require('../assests/icons/svg/electricity.png') },
  { id: 3, name: 'DTH', value: 'Dth', icon: require('../assests/icons/svg/dth.png') },
  { id: 4, name: 'Gas', value: 'gasOperators', icon: require('../assests/icons/svg/gas.png') },

];
export const Travel = [
  { id: 1, name: 'Flight', value: 'flightForm', icon: require('../assests/icons/svg/flight.png') },
  { id: 2, name: 'Metro', value: 'Metro', icon: require('../assests/icons/svg/train.png') },
  { id: 3, name: 'Bus', value: 'Bus', icon: require('../assests/icons/svg/bus.png') },
  { id: 4, name: 'FASTag', value: 'Fasttag', icon: require('../assests/icons/fast.png') },
  // { id: 1, name: 'Flight', icon: <SvgComponent /> },
];

export const yatraDetails = [
  {
    id: 1, name: 'CHARDHAM YATRA PACKAGE', image: require('../assests/images/yatra1.png'), data: [
      { title: '3', icon: require('../assests/icons/helicopter.png') },
      { title: '5', icon: require('../assests/icons/kedarnath.png') },
      { title: '7', icon: require('../assests/icons/helicopter.png') },
      { title: '10', icon: require('../assests/icons/kedarnath.png') },
    ]
  },
  {
    id: 2, name: 'DODHAM YATRA PACKAGE', image: require('../assests/images/dodham.png'), data: [
      { title: '3', icon: require('../assests/icons/helicopter.png') },
      { title: '5', icon: require('../assests/icons/kedarnath.png') },
      { title: '7', icon: require('../assests/icons/helicopter.png') },
      { title: '10', icon: require('../assests/icons/kedarnath.png') },
    ]
  },
  {
    id: 3, name: 'CHARDHAM YATRA PACKAGE', image: require('../assests/images/dodham.png'), data: [
      { title: '3', icon: require('../assests/icons/helicopter.png') },
      { title: '5', icon: require('../assests/icons/kedarnath.png') },
      { title: '7', icon: require('../assests/icons/helicopter.png') },
      { title: '10', icon: require('../assests/icons/kedarnath.png') },
    ]
  },
  {
    id: 4, name: 'MANALI YATRA PACKAGE', image: require('../assests/images/dodham.png'), data: [
      { title: '3', icon: require('../assests/icons/helicopter.png') },
      { title: '5', icon: require('../assests/icons/kedarnath.png') },
      { title: '7', icon: require('../assests/icons/helicopter.png') },
      { title: '10', icon: require('../assests/icons/kedarnath.png') },
    ]
  }
]
export const paymentdata = [
  { id: 1, name: 'Paytm UPI', icon: require('../assests/icons/paytm.png') },
  { id: 2, name: 'Google Pay', icon: require('../assests/icons/googlepay.png') },
  { id: 3, name: 'Phonepe UPI', icon: require('../assests/icons/phonepay.png') },
  { id: 4, name: 'Amazone Pay Balance', icon: require('../assests/icons/amazonpay.png') },

];
export const cardData = [
  { id: 1, name: 'Credit / Debit Card', icon: require('../assests/icons/card.png') },
  { id: 2, name: 'Wallets', icon: require('../assests/icons/walletcard.png') },
  { id: 3, name: 'Net banking', icon: require('../assests/icons/netbanking.png') },
  { id: 4, name: 'Cash ', icon: require('../assests/icons/cash.png') },

];
export const cabinclass = [
  // {
  //   id: 1,
  //   name: 'ALL',
  //   // image: require('../../../assests/images/economy.png')
  // },
  {
    id: 2,
    name: 'Economy',
    // image: require('../../../assests/images/economy.png')
  },
  {
    id: 3,
    name: 'PremiumEconomy',
    // image: require('../../../assests/images/economy.png')
  },
  {
    id: 4,
    name: 'Business',
    // image: require('../../../assests/images/economy.png')
  },
  {
    id: 5,
    name: 'PremiumBusiness',
    // image: require('../../../assests/images/economy.png')
  },
  {
    id: 6,
    name: 'First',
    // image: require('../../../assests/images/economy.png')
  },

]

export const RowSeats = [
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "7A",
        "RowNo": "7",
        "SeatNo": "A",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "7B",
        "RowNo": "7",
        "SeatNo": "B",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "7C",
        "RowNo": "7",
        "SeatNo": "C",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "7D",
        "RowNo": "7",
        "SeatNo": "D",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "7E",
        "RowNo": "7",
        "SeatNo": "E",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "7F",
        "RowNo": "7",
        "SeatNo": "F",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Right side of aircraft. "
      }
    ]
  },
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "8A",
        "RowNo": "8",
        "SeatNo": "A",
        "SeatType": 5,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "8B",
        "RowNo": "8",
        "SeatNo": "B",
        "SeatType": 17,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 3,
        "Description": 2,
        "Code": "8C",
        "RowNo": "8",
        "SeatNo": "C",
        "SeatType": 11,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "8D",
        "RowNo": "8",
        "SeatNo": "D",
        "SeatType": 11,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "8E",
        "RowNo": "8",
        "SeatNo": "E",
        "SeatType": 17,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "8F",
        "RowNo": "8",
        "SeatNo": "F",
        "SeatType": 5,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Right side of aircraft. "
      }
    ]
  },
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "9A",
        "RowNo": "9",
        "SeatNo": "A",
        "SeatType": 5,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "9B",
        "RowNo": "9",
        "SeatNo": "B",
        "SeatType": 17,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "9C",
        "RowNo": "9",
        "SeatNo": "C",
        "SeatType": 11,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 3,
        "Description": 2,
        "Code": "9D",
        "RowNo": "9",
        "SeatNo": "D",
        "SeatType": 11,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "9E",
        "RowNo": "9",
        "SeatNo": "E",
        "SeatType": 17,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "9F",
        "RowNo": "9",
        "SeatNo": "F",
        "SeatType": 5,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      }
    ]
  },
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "10A",
        "RowNo": "10",
        "SeatNo": "A",
        "SeatType": 9,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "10B",
        "RowNo": "10",
        "SeatNo": "B",
        "SeatType": 21,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "10C",
        "RowNo": "10",
        "SeatNo": "C",
        "SeatType": 15,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "10D",
        "RowNo": "10",
        "SeatNo": "D",
        "SeatType": 15,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "10E",
        "RowNo": "10",
        "SeatNo": "E",
        "SeatType": 21,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "10F",
        "RowNo": "10",
        "SeatNo": "F",
        "SeatType": 9,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      }
    ]
  },
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "11A",
        "RowNo": "11",
        "SeatNo": "A",
        "SeatType": 9,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "11B",
        "RowNo": "11",
        "SeatNo": "B",
        "SeatType": 21,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "11C",
        "RowNo": "11",
        "SeatNo": "C",
        "SeatType": 15,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "11D",
        "RowNo": "11",
        "SeatNo": "D",
        "SeatType": 15,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "11E",
        "RowNo": "11",
        "SeatNo": "E",
        "SeatType": 21,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "11F",
        "RowNo": "11",
        "SeatNo": "F",
        "SeatType": 9,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      }
    ]
  },
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "12A",
        "RowNo": "12",
        "SeatNo": "A",
        "SeatType": 5,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "12B",
        "RowNo": "12",
        "SeatNo": "B",
        "SeatType": 17,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "12C",
        "RowNo": "12",
        "SeatNo": "C",
        "SeatType": 11,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "12D",
        "RowNo": "12",
        "SeatNo": "D",
        "SeatType": 11,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "12E",
        "RowNo": "12",
        "SeatNo": "E",
        "SeatType": 17,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "12F",
        "RowNo": "12",
        "SeatNo": "F",
        "SeatType": 5,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      }
    ]
  },
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 3,
        "Description": 2,
        "Code": "13A",
        "RowNo": "13",
        "SeatNo": "A",
        "SeatType": 50,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 3,
        "Description": 2,
        "Code": "13B",
        "RowNo": "13",
        "SeatNo": "B",
        "SeatType": 50,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 3,
        "Description": 2,
        "Code": "13C",
        "RowNo": "13",
        "SeatNo": "C",
        "SeatType": 50,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 3,
        "Description": 2,
        "Code": "13D",
        "RowNo": "13",
        "SeatNo": "D",
        "SeatType": 50,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 3,
        "Description": 2,
        "Code": "13E",
        "RowNo": "13",
        "SeatNo": "E",
        "SeatType": 50,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 3,
        "Description": 2,
        "Code": "13F",
        "RowNo": "13",
        "SeatNo": "F",
        "SeatType": 50,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0
      }
    ]
  },
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "14A",
        "RowNo": "14",
        "SeatNo": "A",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "14B",
        "RowNo": "14",
        "SeatNo": "B",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "14C",
        "RowNo": "14",
        "SeatNo": "C",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "14D",
        "RowNo": "14",
        "SeatNo": "D",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "14E",
        "RowNo": "14",
        "SeatNo": "E",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "14F",
        "RowNo": "14",
        "SeatNo": "F",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Right side of aircraft. "
      }
    ]
  },
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "15A",
        "RowNo": "15",
        "SeatNo": "A",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "15B",
        "RowNo": "15",
        "SeatNo": "B",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "15C",
        "RowNo": "15",
        "SeatNo": "C",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "15D",
        "RowNo": "15",
        "SeatNo": "D",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "15E",
        "RowNo": "15",
        "SeatNo": "E",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "15F",
        "RowNo": "15",
        "SeatNo": "F",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Right side of aircraft. "
      }
    ]
  },
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "16A",
        "RowNo": "16",
        "SeatNo": "A",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "16B",
        "RowNo": "16",
        "SeatNo": "B",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "16C",
        "RowNo": "16",
        "SeatNo": "C",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "16D",
        "RowNo": "16",
        "SeatNo": "D",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "16E",
        "RowNo": "16",
        "SeatNo": "E",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "16F",
        "RowNo": "16",
        "SeatNo": "F",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Right side of aircraft. "
      }
    ]
  },
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "17A",
        "RowNo": "17",
        "SeatNo": "A",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "17B",
        "RowNo": "17",
        "SeatNo": "B",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "17C",
        "RowNo": "17",
        "SeatNo": "C",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "17D",
        "RowNo": "17",
        "SeatNo": "D",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "17E",
        "RowNo": "17",
        "SeatNo": "E",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "17F",
        "RowNo": "17",
        "SeatNo": "F",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Right side of aircraft. "
      }
    ]
  },
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "18A",
        "RowNo": "18",
        "SeatNo": "A",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "18B",
        "RowNo": "18",
        "SeatNo": "B",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "18C",
        "RowNo": "18",
        "SeatNo": "C",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "18D",
        "RowNo": "18",
        "SeatNo": "D",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "18E",
        "RowNo": "18",
        "SeatNo": "E",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "18F",
        "RowNo": "18",
        "SeatNo": "F",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 1,
        "Currency": "INR",
        "Price": 0,
        "Text": "Right side of aircraft. "
      }
    ]
  },
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "19A",
        "RowNo": "19",
        "SeatNo": "A",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "19B",
        "RowNo": "19",
        "SeatNo": "B",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "19C",
        "RowNo": "19",
        "SeatNo": "C",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "19D",
        "RowNo": "19",
        "SeatNo": "D",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "19E",
        "RowNo": "19",
        "SeatNo": "E",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "19F",
        "RowNo": "19",
        "SeatNo": "F",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Right side of aircraft. "
      }
    ]
  },
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "20A",
        "RowNo": "20",
        "SeatNo": "A",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "20B",
        "RowNo": "20",
        "SeatNo": "B",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "20C",
        "RowNo": "20",
        "SeatNo": "C",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "20D",
        "RowNo": "20",
        "SeatNo": "D",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "20E",
        "RowNo": "20",
        "SeatNo": "E",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "20F",
        "RowNo": "20",
        "SeatNo": "F",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Right side of aircraft. "
      }
    ]
  },
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "21A",
        "RowNo": "21",
        "SeatNo": "A",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "21B",
        "RowNo": "21",
        "SeatNo": "B",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "21C",
        "RowNo": "21",
        "SeatNo": "C",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "21D",
        "RowNo": "21",
        "SeatNo": "D",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "21E",
        "RowNo": "21",
        "SeatNo": "E",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "21F",
        "RowNo": "21",
        "SeatNo": "F",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Right side of aircraft. "
      }
    ]
  },
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "22A",
        "RowNo": "22",
        "SeatNo": "A",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "22B",
        "RowNo": "22",
        "SeatNo": "B",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "22C",
        "RowNo": "22",
        "SeatNo": "C",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "22D",
        "RowNo": "22",
        "SeatNo": "D",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "22E",
        "RowNo": "22",
        "SeatNo": "E",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "22F",
        "RowNo": "22",
        "SeatNo": "F",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Right side of aircraft. "
      }
    ]
  },
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "23A",
        "RowNo": "23",
        "SeatNo": "A",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "23B",
        "RowNo": "23",
        "SeatNo": "B",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "23C",
        "RowNo": "23",
        "SeatNo": "C",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "23D",
        "RowNo": "23",
        "SeatNo": "D",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "23E",
        "RowNo": "23",
        "SeatNo": "E",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "23F",
        "RowNo": "23",
        "SeatNo": "F",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Right side of aircraft. "
      }
    ]
  },
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "24A",
        "RowNo": "24",
        "SeatNo": "A",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "24B",
        "RowNo": "24",
        "SeatNo": "B",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "24C",
        "RowNo": "24",
        "SeatNo": "C",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "24D",
        "RowNo": "24",
        "SeatNo": "D",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "24E",
        "RowNo": "24",
        "SeatNo": "E",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "24F",
        "RowNo": "24",
        "SeatNo": "F",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Right side of aircraft. "
      }
    ]
  },
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "25A",
        "RowNo": "25",
        "SeatNo": "A",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "25B",
        "RowNo": "25",
        "SeatNo": "B",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "25C",
        "RowNo": "25",
        "SeatNo": "C",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "25D",
        "RowNo": "25",
        "SeatNo": "D",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "25E",
        "RowNo": "25",
        "SeatNo": "E",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "25F",
        "RowNo": "25",
        "SeatNo": "F",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Right side of aircraft. "
      }
    ]
  },
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "26A",
        "RowNo": "26",
        "SeatNo": "A",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "26B",
        "RowNo": "26",
        "SeatNo": "B",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "26C",
        "RowNo": "26",
        "SeatNo": "C",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "26D",
        "RowNo": "26",
        "SeatNo": "D",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "26E",
        "RowNo": "26",
        "SeatNo": "E",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "26F",
        "RowNo": "26",
        "SeatNo": "F",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Right side of aircraft. "
      }
    ]
  },
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "27A",
        "RowNo": "27",
        "SeatNo": "A",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "27B",
        "RowNo": "27",
        "SeatNo": "B",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "27C",
        "RowNo": "27",
        "SeatNo": "C",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "27D",
        "RowNo": "27",
        "SeatNo": "D",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "27E",
        "RowNo": "27",
        "SeatNo": "E",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "27F",
        "RowNo": "27",
        "SeatNo": "F",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Right side of aircraft. "
      }
    ]
  },
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "28A",
        "RowNo": "28",
        "SeatNo": "A",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "28B",
        "RowNo": "28",
        "SeatNo": "B",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 3,
        "Description": 2,
        "Code": "28C",
        "RowNo": "28",
        "SeatNo": "C",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "28D",
        "RowNo": "28",
        "SeatNo": "D",
        "SeatType": 2,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "28E",
        "RowNo": "28",
        "SeatNo": "E",
        "SeatType": 3,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "28F",
        "RowNo": "28",
        "SeatNo": "F",
        "SeatType": 1,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Right side of aircraft. "
      }
    ]
  },
  {
    "Seats": [
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "29A",
        "RowNo": "29",
        "SeatNo": "A",
        "SeatType": 4,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "29B",
        "RowNo": "29",
        "SeatNo": "B",
        "SeatType": 16,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "29C",
        "RowNo": "29",
        "SeatNo": "C",
        "SeatType": 10,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Left side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 3,
        "Description": 2,
        "Code": "29D",
        "RowNo": "29",
        "SeatNo": "D",
        "SeatType": 10,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "29E",
        "RowNo": "29",
        "SeatNo": "E",
        "SeatType": 16,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Seat not allowed for Adults with Infants. Right side of aircraft. "
      },
      {
        "AirlineCode": "UK",
        "FlightNumber": "851",
        "CraftType": "320",
        "Origin": "BOM",
        "Destination": "BLR",
        "AvailablityType": 1,
        "Description": 2,
        "Code": "29F",
        "RowNo": "29",
        "SeatNo": "F",
        "SeatType": 4,
        "SeatWayType": 2,
        "Compartment": 1,
        "Deck": 2,
        "Currency": "INR",
        "Price": 0,
        "Text": "Right side of aircraft. "
      }
    ]
  }
]